trigger:
- azure_pipelines

jobs:
- job:
  displayName: WindowsAgent
  pool: 'Default'

  strategy:
    matrix:
      64-bit Release:
        BuildType: RelWithDebInfo
        CMakeArgs: '"Visual Studio 15 2017 Win64"'
        BuildFolder: '$(Build.BinariesDirectory)\build'
        InstallFolder: '$(Build.BinariesDirectory)\install'
        Variant: '--build-relwithdebug'

  steps:

     - task: UsePythonVersion@0
       inputs:
        versionSpec: '2.x' 
        addToPath: true 
        architecture: 'x64' # Options: x86, x64 (this argument applies only on Windows agents)
       displayName: Use python 2.7!

     - script: pip.exe list
       displayName: 'list python packages'

     - script: |
        SET PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64";%PATH%
        echo %PATH%

     - script: python build_scripts/build_usd.py $(InstallFolder)
       displayName: 'Run build script!'
