trigger:
- dev

jobs:
- job:
  displayName: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7'
        addToPath: true
      displayName: Use python2.7!
