trigger:
- azure_pipelines

jobs:
- job:
  displayName: Windows
  pool: 'Default'

  strategy:
    matrix:
      64-bit Release:
        BuildType: RelWithDebInfo
        CMakeArgs: '"Visual Studio 15 2017 Win64"'
        BuildFolder: '$(Build.BinariesDirectory)\build'
        InstallFolder: '$(Build.BinariesDirectory)\install'
        Variant: '--build-relwithdebug'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7'
        addToPath: true
      displayName: Use python2.7!

    - script: python build_scripts/build_usd.py $(InstallFolder)
      displayName: 'Run build script!'
